using UnityEngine;
using UnityEngine.SceneManagement;

public class DoorTrigger : MonoBehaviour
{
    public string nextSceneName;              // РЬЕПЧв ОР РЬИЇ
    public Animator doorAnimator;             // ЙЎ ОжДЯИоРЬХЭ
    private bool triggered = false;           // СпКЙ НЧЧр ЙцСі

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (triggered) return;

        if (collision.CompareTag("Player"))
        {
            triggered = true;

            // ЙЎ ОжДЯИоРЬМЧ НЧЧр
            if (doorAnimator != null)
                doorAnimator.SetTrigger("Open");
            SceneManager.LoadScene(nextSceneName);
        }
    }

    // ОжДЯИоРЬМЧ ГЁГЊДТ СіСЁПЁМ­ Animation EventЗЮ ШЃУт
    public void OnDoorOpened()
    {
        if (!string.IsNullOrEmpty(nextSceneName))
        {
            SceneManager.LoadScene(nextSceneName);
        }
        else
        {
            Debug.LogWarning("nextSceneNameРЬ КёОюРжНРДЯДй!");
        }
    }
}
